#!/bin/sh -e

LEVEL=$1
case ${LEVEL} in
	0|6)
		for SERVICE in $(ls /run/service)
		do
			sv force-stop ${SERVICE} || true
		done

		SIG_LEVEL0=USR1
		SIG_LEVEL6=INT
		eval "SIG=\${SIG_LEVEL${LEVEL}}"

		kill -${SIG} 1
		;;
	*)
		RUN_LEVEL_DIR="/etc/runit/runsvdir/$1"
		if [ ! -e "${RUN_LEVEL_DIR}" ]
		then
			echo "Invalid level: $1" 2>1
			exit 1
		fi

		STAGING_DIR="/run/runit/$1"
		rm -rf ${STAGING_DIR}
		mkdir -p ${STAGING_DIR}
		for SERVICE in $(ls ${RUN_LEVEL_DIR})
		do
			mkdir -p ${STAGING_DIR}/${SERVICE}
			cp -r /etc/runit/runsvdir/$1/${SERVICE}/* ${STAGING_DIR}/${SERVICE}/
		done

		rm -rf /run/service
		ln -s ${STAGING_DIR} /run/service
		;;
esac
