MONERO_VERSION = 793bc973746a10883adb2f89827e223f562b9651
MONERO_SITE = $(call github,monero-project,monero,$(MONERO_VERSION))
MONERO_LICENSE_FILES = LICENSE
MONERO_CONF_OPTS = \
	-DARCH="armv6zk" \
	-DBUILD_TESTS=OFF \
	-DTHREADS_PTHREAD_ARG=0 \
	-DBUILD_DOCUMENTATION=OFF \
	-DBUILD_SHARED_LIBS=OFF \
	-DUPNP_STATIC=ON \
	-DUSE_READLINE=OFF \
	-DSTATIC=ON \
	-DCMAKE_BUILD_TYPE=minsizerel
MONERO_DEPENDENCIES += boost openssl cppzmq
MONERO_MAKE_OPTS = simplewallet
MONERO_INSTALL_TARGET_OPTS =

define MONERO_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/bin/monero-wallet-cli $(TARGET_DIR)/bin/monero-wallet-cli
endef

$(eval $(cmake-package))
