CPP_ETHEREUM_VERSION = ee0c6776c01b09045a379220c7e490000dae9377
CPP_ETHEREUM_SITE = https://github.com/ethereum/cpp-ethereum.git
CPP_ETHEREUM_SITE_METHOD = git
CPP_ETHEREUM_GIT_SUBMODULES = YES
CPP_ETHEREUM_LICENSE = GPLv3
CPP_ETHEREUM_LICENSE_FILES = LICENSE
CPP_ETHEREUM_DEPENDENCIES = leveldb
CPP_ETHEREUM_INSTALL_TARGET_OPTS =
CPP_ETHEREUM_CONF_OPTS = \
	-DEVMJIT=OFF \
	-DTESTS=OFF \
	-DMINIUPNPC=OFF \
	-DHUNTER_JOBS_NUMBER=$(shell nproc) \
	-DHUNTER_ROOT=$(BUILD_DIR)/hunter
	-DHERA=OFF
CPP_ETHEREUM_MAKE_OPTS = ethkey
CPP_ETHEREUM_PRE_CONFIGURE_HOOKS += CPP_ETHEREUM_WORKAROUND

define CPP_ETHEREUM_INSTALL_TARGET_CMDS
	$(INSTALL) -D -m 0755 $(@D)/ethkey/ethkey $(TARGET_DIR)/bin/ethkey
endef

define CPP_ETHEREUM_WORKAROUND
	mkdir -p "$(STAGING_DIR)/include"
endef

$(eval $(cmake-package))
