#!/bin/sh

detect-container && exit 0 || true

DEV_BUTTON=$(cat /sys/class/gpio/gpio6/value)
if [ "${DEV_BUTTON}" = "0" ]
then
	DEV_MODE=1
else
	DEV_MODE=0
fi
export DEV_MODE

cd /sys/kernel/config/usb_gadget/
mkdir -p hakomari
cd hakomari

echo 0x1d6b > idVendor # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB # USB2

mkdir -p strings/0x409
SERIAL=$(cat /proc/cpuinfo | grep 'Serial' | cut -d':' -f2)
SERIAL="${SERIAL## }"
echo "${SERIAL}" > strings/0x409/serialnumber
echo "bullno1" > strings/0x409/manufacturer
echo "Hakomari USB Device" > strings/0x409/product

mkdir -p configs/c.1/strings/0x409
echo "Config 1: Dev Mode" > configs/c.1/strings/0x409/configuration
echo 350 > configs/c.1/MaxPower

mkdir -p functions/acm.usb0
ln -s functions/acm.usb0 configs/c.1/

if [ "${DEV_MODE}" = 1 ]
then
	mkdir -p functions/acm.usb1
	ln -s functions/acm.usb1 configs/c.1/

	mkdir -p functions/ecm.usb0
	# first byte of address must be even
	HOST="48:6f:73:74:50:43" # "HostPC"
	SELF="42:61:64:55:53:42" # "BadUSB"
	echo $HOST > functions/ecm.usb0/host_addr
	echo $SELF > functions/ecm.usb0/dev_addr
	ln -s functions/ecm.usb0 configs/c.1/
fi

ls /sys/class/udc > UDC
