#!/bin/sh

BINDIR=$(dirname $0)
TARGETDIR="${BINDIR}/../output/target"
INTERPRETER="$(which qemu-arm-static)"

touch ${TARGETDIR}/${INTERPRETER}
touch ${TARGETDIR}/dev/urandom

PIDFILE=/tmp/hakomari.pid

mkdir -p ${TARGETDIR}/.hako

exec sudo ${BINDIR}/../output/host/sbin/hako-run \
	--mount ${INTERPRETER}:${INTERPRETER}:ro \
	--mount /dev/urandom:/dev/urandom:ro \
	--pid-file=${PIDFILE} \
	${TARGETDIR} "$@"
