#!/bin/sh

NEWROOT="$1"
BINDIR=$(dirname $0)
INTERPRETER="$(which qemu-arm-static)"

touch output/target/${INTERPRETER}

PIDFILE=/tmp/hakomari.pid
LOGDIR=/tmp/hakomari.log

mkdir -p ${LOGDIR}
mkdir -p ${NEWROOT}/.hako

exec ${BINDIR}/../output/host/sbin/hako-run \
	--mount ${INTERPRETER}:${INTERPRETER}:ro \
	--mount ${LOGDIR}:/var/log \
	--pid-file=${PIDFILE} \
	"$@"
