#ifndef HAKOMARI_CFG_H
#define HAKOMARI_CFG_H

#ifndef HAKOMARI_RUN_PATH
#define HAKOMARI_RUN_PATH "/var/run/hakomari"
#endif

#ifndef HAKOMARI_PROVIDER_PATH
#define HAKOMARI_PROVIDER_PATH HAKOMARI_RUN_PATH "/providers"
#endif

#ifndef HAKOMARI_DISPLAYD_SOCK_PATH
#define HAKOMARI_DISPLAYD_SOCK_PATH HAKOMARI_RUN_PATH "/displayd/sock"
#endif

#define HAKOMARI_EXIT_CODE_OFFSET 64

typedef enum hakomari_error_e
{
	HAKOMARI_OK,
	HAKOMARI_ERR_INVALID,
	HAKOMARI_ERR_MEMORY,
	HAKOMARI_ERR_AUTH_REQUIRED,
	HAKOMARI_ERR_DENIED,
	HAKOMARI_ERR_IO,
} hakomari_error_t;

#endif
