LIBANCILLARY_VERSION = 657009b587d28e910655c068465422b1de3313a4
LIBANCILLARY_SITE = https://gitorious.org/libancillary/libancillary.git
LIBANCILLARY_SITE_METHOD = git
LIBANCILLARY_LICENSE = BSD
LIBANCILLARY_LICENSE_FILES = COPYING
LIBANCILLARY_INSTALL_STAGING = YES
LIBANCILLARY_INSTALL_TARGET = NO

define LIBANCILLARY_BUILD_CMDS
	$(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D)
endef

define LIBANCILLARY_INSTALL_STAGING_CMDS
	$(INSTALL) -D -m 0644 $(@D)/libancillary.a $(STAGING_DIR)/lib/
	$(INSTALL) -D -m 0644 $(@D)/ancillary.h $(STAGING_DIR)/usr/include
endef

$(eval $(generic-package))
